SET storage_engine=InnoDB;
CREATE DATABASE IF NOT EXISTS Tribunale;
USE Tribunale;
SET FOREIGN_KEY_CHECKS=1;

DROP TABLE IF EXISTS UDIENZA;
DROP TABLE IF EXISTS CAUSA;
DROP TABLE IF EXISTS AULA_TRIBUNALE;
DROP TABLE IF EXISTS TRIBUNALE;
DROP TABLE IF EXISTS GIUDICE;

CREATE TABLE GIUDICE(
  CodFiscale CHAR(16),
  Nome VARCHAR(20) NOT NULL,
  Cognome VARCHAR(20) NOT NULL,
  DataNascita DATE NOT NULL,
  PRIMARY KEY(CodFiscale)
);

CREATE TABLE TRIBUNALE(
  CodTribunale CHAR(2),
  NomeTribunale VARCHAR(20) NOT NULL,
  Citta VARCHAR(20) NOT NULL,
  PRIMARY KEY(CodTribunale)
);

CREATE TABLE AULA_TRIBUNALE(
  CodTribunale CHAR(2),
  CodAula CHAR(5),
  NomeAula CHAR(20) NOT NULL,
  PRIMARY KEY(CodTribunale, CodAula),
  FOREIGN KEY(CodTribunale) REFERENCES TRIBUNALE(CodTribunale)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE CAUSA(
  CodCausa CHAR(2),
  TipologiaCausa VARCHAR(20) NOT NULL,
  DataInizio DATE NOT NULL,
  DataFine DATE NULL,
  CodFiscale CHAR(16) NOT NULL,
  PRIMARY KEY(CodCausa),
  FOREIGN KEY(CodFiscale) REFERENCES GIUDICE(CodFiscale)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);

CREATE TABLE UDIENZA(
  CodTribunale CHAR(2),
  CodAula CHAR(5),
  Data DATE,
  OraInizio TIME NOT NULL,
  OraFine TIME NOT NULL,
  CodCausa CHAR(2) NOT NULL,
  PRIMARY KEY(CodTribunale, CodAula, Data),
  FOREIGN KEY(CodCausa) REFERENCES CAUSA(CodCausa)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY(CodTribunale, CodAula) REFERENCES AULA_TRIBUNALE(CodTribunale, CodAula)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
