SET storage_engine=InnoDB;
CREATE DATABASE IF NOT EXISTS Palestra2;
USE Palestra2;
SET FOREIGN_KEY_CHECKS=1;

DROP TABLE IF EXISTS LEZIONE;
DROP TABLE IF EXISTS SPECIALITA;
DROP TABLE IF EXISTS PALESTRA;
DROP TABLE IF EXISTS ISTRUTTORE;

CREATE TABLE ISTRUTTORE(
  CodFiscale CHAR(16),
  NomeT VARCHAR(20) NOT NULL,
  Cognome VARCHAR(20) NOT NULL,
  Citta VARCHAR(20) NOT NULL,
  PRIMARY KEY(CodFiscale)
);

CREATE TABLE PALESTRA(
  CodP CHAR(2),
  NomeP VARCHAR(20) NOT NULL,
  Indirizzo VARCHAR(20) NOT NULL,
  Citta VARCHAR(20) NOT NULL,
  PRIMARY KEY(CodP)
);

CREATE TABLE SPECIALITA(
  CodS CHAR(2),
  NomeS VARCHAR(20) NOT NULL,
  Descrizione VARCHAR(50) NOT NULL,
  PRIMARY KEY(CodS)
);

CREATE TABLE LEZIONE(
  CodFiscale CHAR(16),
  CodP CHAR(2),
  Data DATE,
  CodS CHAR(2) NOT NULL,
  NumPartecipanti SMALLINT NOT NULL,
  PRIMARY KEY(CodFiscale, CodP, Data),
  FOREIGN KEY(CodFiscale) REFERENCES ISTRUTTORE(CodFiscale)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY(CodP) REFERENCES PALESTRA(CodP)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
  FOREIGN KEY(CodS) REFERENCES SPECIALITA(CodS)
  ON DELETE CASCADE
  ON UPDATE CASCADE
);
