CREATE OR REPLACE TRIGGER es1
BEFORE UPDATE OF DNAME ON DIP
FOR EACH ROW
WHEN (OLD.DNAME = 'ACCOUNTING' AND NEW.DNAME = 'SALES')
BEGIN
  UPDATE IMP
  SET SAL = SAL + 100
  WHERE IMP.DEPTNO = :NEW.DEPTNO
END;
